exp_id: 003-GAN_noisy_cond_hinge
tigge_dir: /datadrive_ssd/tigge/32km/
tigge_vars: [total_precipitation]
mrms_dir: /datadrive_ssd/mrms/4km/RadarOnly_QPE_06H/
rq_fn: /datadrive_ssd/mrms/4km/RadarQuality.nc
save_dir: /datadrive_ssd/saved_models
epochs: 25
nres: 3
nf: 64
relu_out: False
sigmoid: False
spectralnorm: True
cond_disc: True
D_loss: Wasserstein